[package]
name = "rust_server"
version = "0.1.0"
authors = ["Robin <robin.stoehr@code.berlin>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
libc = "0.2.77"
rexsgdata = "0.9.7"
