version: "3"
services:
  conversation-postgres:
    image: "postgres:11"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: